// <auto-generated />
using HesapMakinesiMVC.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HesapMakinesiMVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240412215116_update-date-type")]
    partial class updatedatetype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HesapMakinesiMVC.Entities.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProcessId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Number1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Number1");

                    b.Property<string>("Number2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Number2");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProcessType");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Result");

                    b.HasKey("ProcessId");

                    b.ToTable("Process", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
